bucket_name: uploadfirebase-e916c.appspot.com
spring:
    application:
        name: firebase_springboot
    config:
        import: env-dev.yml
    datasource:
        url: jdbc:mysql://localhost:3306/handle_exception?createDatabaseIfNotExist=true
        password: ${spring.datasource.password}
        username: ${spring.datasource.root}
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
                jdbc:
                    time_zone: UTC